version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/layered/buildSrc"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/layered/buildSrc/src/main/groovy"
    schedule:
      interval: "daily"
